package plausibcheck.adress

import com.neo.drools.model.Address;
import com.neo.drools.model.State;
import com.neo.drools.model.fact.AddressCheckResult;
import com.neo.drools.action.TestAction;

rule "Postcode should be filled with exactly 6 numbers"
    when
        address : Address(postcode != null, postcode matches "([0-9]{6})")
        state : State(name == address.state)
        checkResult : AddressCheckResult()
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：校验通过!");
		System.out.println("state.name="+state.getName());
		new TestAction().loveWhoWho(state.getName());
end